/*!

\page create_smoothingsurface_page Smoothing Surface

To create a <b> Smoothing Surface</b> in the <b>Main Menu</b> select <b>New Entity - >
Advanced - > SmoothingSurface </b>

Specify the \b Name of the surface and the list of \b Points, from which it is approximated and press "Apply" or "Apply & Close" button.

The result of the operation will be a GEOM_Object(Surface).

<b>TUI Command:</b> <em>geompy.MakeSmoothingSurface(Points)</em>

\image html smoothingsurface_dlg.png

Example:

\image html smoothingsurface.png

Our <b>TUI Scripts</b> provide you with useful examples of creation of
\ref tui_creation_smoothingsurface "Advanced objects".

*/
