/*!

\page create_smoothingsurface_page Smoothing Surface

To create a <b> Smoothing Surface</b> in the <b>Main Menu</b> select <b>New Entity - >
Advanced - > SmoothingSurface </b>

\image html smoothingsurface_dlg.png

In this dialog you can specify the following parameters:
- \b Name of the surface; 
- the list of \b Points or compounds of points, from which it is approximated;
- <b>Max nbr of Bezier pieces</b> in the resulting surface;
- <b>Max BSpline surface degree</b> of the resulting BSpline surface;
- <b>Max plate criterion value</b>, which is computed as <em> max(0.0001,10*error), </em> where error is a 3D tolerance of the surface.

Press "Apply" or "Apply & Close" button to get the resulting <em>GEOM_Object(Surface)</em>.

<b>TUI Command:</b> <em>geompy.MakeSmoothingSurface(thelPoints, theNbMax, theDegMax, theDMax)</em>, where:
- \em thelPoints is a list of points or compounds of points;
- \em theNbMax maximum number of Bezier pieces in the resulting surface;
- \em theDegMax maximum degree;  
- \em theDMax specifies maximum value of <em> GeomPlate_PlateG0Criterion </em>.

Example:

\image html smoothingsurface.png

Our <b>TUI Scripts</b> provide you with useful examples of creation of
\ref tui_creation_smoothingsurface "Advanced objects".

*/
